dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${properties["kotlinVersion"]}")
    implementation("org.jetbrains.kotlin:kotlin-reflect:${properties["kotlinVersion"]}")
    implementation("org.jetbrains.kotlin:kotlin-test:${properties["kotlinVersion"]}")
    implementation("com.google.guava:guava:${properties["guavaVersion"]}")
    implementation("com.nhaarman:mockito-kotlin:${properties["mockitoKotlinVersion"]}")
    implementation("junit:junit:${properties["junitVersion"]}")
    implementation("io.reactivex:rxjava:${properties["rxjavaVersion"]}")
    implementation("org.junit.jupiter:junit-jupiter-api:${properties["junitJupiterVersion"]}")
    implementation("org.apache.activemq:artemis-core-client:${properties["artemisVersion"]}")
    implementation("org.apache.activemq:artemis-server:${properties["artemisVersion"]}")
    implementation("org.apache.activemq:artemis-amqp-protocol:${properties["artemisVersion"]}")
    implementation("org.hamcrest:hamcrest-library:${properties["hamcrestVersion"]}")
    implementation("com.natpryce:hamkrest:${properties["hamkrestVersion"]}")
    implementation("org.apache.activemq:artemis-commons:${properties["artemisVersion"]}")
    implementation("org.slf4j:slf4j-api:${properties["slf4jVersion"]}")
    implementation("org.bouncycastle:bcprov-jdk15on:${properties["bouncycastleVersion"]}")
    implementation("org.bouncycastle:bcpkix-jdk15on:${properties["bouncycastleVersion"]}")

    implementation(project(":core"))
    implementation(project(":node-api"))
    implementation(project(":test-common"))
    implementation(project(":serialization"))

    testImplementation("org.assertj:assertj-core:${properties["assertjVersion"]}")
}