/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    id("org.ajoberstar.grgit") version "4.0.2"

    id("com.jfrog.artifactory") version "4.17.2"

    `maven-publish`

    `java-library`
}

repositories {
    val cordaUseCache = System.getenv("CORDA_USE_CACHE")
    if(cordaUseCache != null) {
        maven(url = "${properties["artifactory_contextUrl"]}/$cordaUseCache") {
            name = "R3 Maven remote repositories"
        }
    } else {
        maven(url = "${properties["artifactory_contextUrl"]}/corda-dependencies-dev")
        maven(url = "${properties["artifactory_contextUrl"]}/corda-releases")
        maven(url = "${properties["artifactory_contextUrl"]}/corda-dependencies") {
            metadataSources {
                mavenPom()
                // TODO: Because Gradle 6.1 will not look for the jar if there is no pom file (https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:dependency-types)
                //       We need to define this.
                //       Ideally we will have a pom file in https://software.r3.com/artifactory/webapp/#/artifacts/browse/tree/General/corda-dependencies/com/github/bft-smart/library/master-v1.1-beta-g6215ec8-87
                //       Or, even better, we should either own this (and make a proper release) or use something from Maven.
                artifact()
            }
        }
        maven(url = "${properties["artifactory_contextUrl"]}/corda-dev")
        maven(url = "${properties["artifactory_contextUrl"]}/testing-ci-uploads-dev-local") {
            credentials {
                username = System.getenv("CORDA_ARTIFACTORY_USERNAME")
                password = System.getenv("CORDA_ARTIFACTORY_PASSWORD")
            }
        }
        mavenCentral()
        jcenter()
        maven(url = "https://kotlin.bintray.com/kotlinx")
        maven(url = "https://repo.gradle.org/gradle/libs-releases-local/")
        mavenLocal()
    }
}

dependencies {
    implementation("com.google.code.findbugs:jsr305:${properties["jsr305Version"]}")
    implementation("io.reactivex:rxjava:${properties["rxjava_version"]}")
    implementation("org.slf4j:slf4j-api:${properties["slf4j_version"]}")
    implementation("co.paralleluniverse:quasar-core:${properties["quasarVersion11"]}")
    implementation("com.github.ben-manes.caffeine:caffeine:${properties["caffeineVersion"]}")
    implementation("org.hibernate:hibernate-core:${properties["hibernate_version"]}")
    implementation("javax.persistence:javax.persistence-api:${properties["persistence-api_version"]}")
    implementation("org.bouncycastle:bcprov-jdk15on:${properties["bouncycastleVersion"]}")
    implementation("org.bouncycastle:bcpkix-jdk15on:${properties["bouncycastleVersion"]}")
    implementation("net.i2p.crypto:eddsa:${properties["eddsa_version"]}")
    implementation("io.netty:netty-common:${properties["netty_version"]}")
    implementation("org.apache.commons:commons-lang3:${properties["commons_lang_version"]}")
    implementation("io.github.classgraph:classgraph:${properties["classgraphVersion"]}")
    implementation("org.jetbrains.kotlin:kotlin-reflect:${properties["kotlinVersion"]}")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${properties["kotlinVersion"]}")

    testImplementation("junit:junit:${properties["junit_version"]}")
    testImplementation("org.jetbrains.kotlin:kotlin-test:${properties["kotlinVersion"]}")
    testImplementation("org.assertj:assertj-core:${properties["assertj_version"]}")
    testImplementation("com.nhaarman:mockito-kotlin:${properties["mockito_kotlin_version"]}")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().forEach { compileKotlin ->
    compileKotlin.kotlinOptions.allWarningsAsErrors = true
    compileKotlin.kotlinOptions.verbose = true
    compileKotlin.kotlinOptions.jvmTarget = "11"
    compileKotlin.kotlinOptions.freeCompilerArgs += "-Xjvm-default=compatibility"
    compileKotlin.kotlinOptions.freeCompilerArgs += "-java-parameters"
}
tasks.withType<JavaCompile>().forEach { compileJava ->
    compileJava.options.compilerArgs.add("-parameters")
}

val branchName = grgit.branch.current().name
val revision = grgit.head().id
val tagName = grgit.tag.list().firstOrNull {
    it.commit.id == revision
}?.name

val baseVersion = properties["cordaVersion"]
if (tagName != null && tagName.startsWith("release-os-")){
    version = tagName.substringAfter("release-os-")
} else if(branchName.startsWith("release/os/")) {
    version = branchName.substringAfter("release/os/") + "-SNAPSHOT"
} else {
    val ticketRegex = Regex("[a-z0-9_]+/(.+)/.+")
    val ticket = ticketRegex.matchEntire(branchName)
    version = (ticket?.groupValues?.get(1)?.toUpperCase() ?: "$baseVersion-$revision") + "-SNAPSHOT"
}

tasks.withType<Jar>().forEach { task ->
    task.manifest {
        attributes("Corda-Release-Version" to version)
        attributes("Corda-Platform-Version" to properties["platformVersion"])
        attributes("Corda-Revision" to revision)
        attributes("Corda-Vendor" to "Corda Open Source")
        attributes("Automatic-Module-Name" to "net.corda.${task.project.name.replace('-', '.')}")
        attributes("Corda-Docs-Link" to "https://docs.corda.net/docs/corda-os/$baseVersion")
    }
}

val javaTestCompiler = tasks.getByName("compileTestJava") as JavaCompile
javaTestCompiler.options.compilerArgs.addAll(listOf("--add-exports",
        "java.base/sun.security.x509=ALL-UNNAMED",
        "--add-exports",
        "java.base/sun.security.util=ALL-UNNAMED"))

val libGroupId = "net.corda"
val libArtifactId = "core"