@Library('corda-shared-build-pipeline-steps')
import static com.r3.build.BuildControl.killAllExistingBuildsForJob

killAllExistingBuildsForJob(env.JOB_NAME, env.BUILD_NUMBER.toInteger())

pipeline {

    agent {
        dockerfile {
            label 'docker'
            additionalBuildArgs "--build-arg USER=buildUser"
            dir '.ci/dev/build-jdk11'
        }
    }

    stages {
        stage("Print specific JDK information") {
            steps {
                sh "java -version"
            }
        }
        stage("Core Tests") {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    sh "./gradlew clean core:test"
                }
            }
        }
    }
}